# -*- coding: utf-8 -*-
"""Webapp.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WLnaIQe_NYeN1ni22ZHJXyYZT_e6Yxr
"""

pip install streamlit

!pip install streamlit
!pip install pyngrok

# Writing the Streamlit app to a file using Python
app_code = """
import streamlit as st
import joblib
import numpy as np
import pandas as pd




# Load your dataset
df = pd.read_csv('crop_yield.csv')


# Get distinct values and join them with a comma
distinct_values_str = ','.join(df['Crop'].unique().astype(str))

columns=['rainfall_x',
 'temperature',
 'Area_in_hectares_x',
 'Crop_arecanut',
 'Crop_ash gourd',
 'Crop_banana',
 'Crop_bitter gourd',
 'Crop_black pepper',
 'Crop_bottle gourd',
 'Crop_brinjal',
 'Crop_cabbage',
 'Crop_carrot',
 'Crop_cauliflower',
 'Crop_cucumber',
 'Crop_grapes',
 'Crop_jute',
 'Crop_mango',
 'Crop_onion',
 'Crop_orange',
 'Crop_papaya',
 'Crop_pineapple',
 'Crop_potato',
 'Crop_rice',
 'Crop_soyabean',
 'Crop_sunflower',
 'Crop_sweet potato',
 'Crop_tomato',
 'Crop_water melon',
 'Season_Autumn     ',
 'Season_Kharif     ',
 'Season_Rabi       ',
 'Season_Summer     ',
 'Season_Whole Year ',
 'Season_Winter     ']

# Load the trained model (ensure this file is available in the notebook environment)
model = joblib.load('crop_yield_predictor_model.pkl')

# Streamlit App
st.title("Crop Yield Prediction Model")

# Create input fields for the user
# Input form for the user
crop = st.selectbox("Select Crop",['Arecanut',
 'Ash gourd',
 'Banana',
 'Bitter gourd',
 'Black pepper',
 'Bottle gourd',
 'Brinjal',
 'Cabbage',
 'Carrot',
 'Cauliflower',
 'Cucumber',
 'Grapes',
 'Jute',
 'Mango',
 'Onion',
 'Orange',
 'Papaya',
 'Pineapple',
 'Potato',
 'Rice',
 'Soyabean',
 'Sunflower',
 'Sweet potato',
 'Tomato',
 'Water melon']
)
season = st.selectbox("Select Season", ['Autumn     ',
 'Kharif     ',
 'Rabi       ',
 'Summer     ',
 'Whole Year ',
 'Winter     '])  # Example seasons
rainfall = st.number_input("Enter Rainfall (mm)", min_value=0.0, step=0.1)  # Example range for rainfall
temperature = st.number_input("Enter Temperature (°C)", min_value=0.0, max_value=50.0, step=0.1)  # Example range for temperature
area_hectares = st.number_input("Enter Area (hectares)", min_value=0.0, step=0.1)  # Example range for area

# Prepare the input data for prediction
input_features = [crop, season, rainfall, temperature, area_hectares]

# Convert the input data into a DataFrame
input_df = pd.DataFrame([input_features], columns=['Crop', 'Season', 'rainfall_x', 'temperature', 'Area_in_hectares_x'])

# One-hot encode the categorical columns ('Crop' and 'Season')
input_df_encoded = pd.get_dummies(input_df, columns=['Crop', 'Season'])

# Ensure the input data aligns with the trained model's feature set
input_df_encoded = input_df_encoded.reindex(columns=columns, fill_value=0)

# Prediction logic
if st.button("Predict Yield"):
    # Prepare the input data for prediction
    input_data = np.array([[crop,season,rainfall,temperature,area_hectares]])

    # Get the prediction from the model
    prediction = model.predict(input_df_encoded)

    # Display the result
    st.write(f"Predicted Crop Yield: {prediction[0]} tons per hectare")    # Display the result
"""

# Save the Streamlit app code to a Python file
with open("app.py", "w") as file:
    file.write(app_code)

print("Streamlit app file ('app.py') created successfully!")

# Step 1: Install required packages
!pip install streamlit
!pip install pyngrok

# Step 2: Authenticate ngrok with your auth token
!ngrok authtoken 2ouHuDR0dncCuooK1yYoXrMNrde_82tJGBshLL1WjDF7sm391  # Replace with your actual auth token

!ngrok authtoken

!pip install --upgrade pyngrok

from pyngrok import ngrok

!ngrok authtoken 2ouHuDR0dncCuooK1yYoXrMNrde_82tJGBshLL1WjDF7sm391

# Now, set up ngrok and create a tunnel to Streamlit's port 8501
public_url = ngrok.connect(8501, "http")  # Make sure to specify "http" instead of "port"
print(f"Streamlit app is available at: {public_url}")

# Now you can run your Streamlit app
!streamlit run app.py &

!streamlit run app.py &